services:
  gmail-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmail-mcp-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - TRANSPORT=streamable-http
    command: ["uv", "run", "server.py"]
    tty: true